Uu button icons
NDLANO/frontend-packages pull request #1007
Opened 2022-01-31 16:23 UTC by peterrolfsen

Added some more Aria tags.

2022-02-01 07:36 UTC, gunnarvelle commented on packages/button/src/MultiButton.tsx
> +  const { t } = useTranslation();
Button-pakka har ikkje react-18next som peer-avhengighet så det må legges til.

2022-02-01 07:36 UTC, gunnarvelle commented on packages/ndla-editor/src/SlateBlockMenu.tsx
> +        <Plus aria-label="Plus" />
Burde denne vore språkhåndtert med `t('menu.plus')` eller nokke sånt?

2022-02-01 07:36 UTC, gunnarvelle commented on packages/ndla-forms/src/PopupWrapper.tsx
> +import { useTranslation } from 'react-i18next';
Har transitiv dependency fra ndla-ui men kanskje like greit å definere som peer.

2022-02-01 07:36 UTC, gunnarvelle commented on packages/ndla-howto/src/StaticInfoComponents/components/FactBoxExample.tsx
> +//@ts-ignore
Trengs ikkje for FactBox er typescript.

2022-02-01 12:14 UTC, gunnarvelle commented on packages/ndla-howto/src/ArticleInModal.tsx
> +import { NotionDialogStyledWrapper } from 'packages/ndla-notion/src/NotionDialog';
Antar denne var inludert ved en feil. Pass uansett på at du importerer med relativ path.

2022-02-01 12:14 UTC, gunnarvelle commented on packages/ndla-howto/src/ArticleInModal.tsx
> +      {console.log(t('close'))}
Slettes.

2022-02-04 14:28 UTC, rfohlin commented on packages/ndla-editor/src/SlateBlockMenu.tsx
> +        <Plus aria-label="Plus" />
Fixade, <Plus /> ignoreras på SR och menyn hanteras istället av aria-props på knappen.

2022-02-04 15:37 UTC, gunnarvelle requested changes
Bruk yarn og ikkje npm. Slett package-lock.json.

2022-02-04 15:37 UTC, gunnarvelle commented on packages/ndla-howto/package-lock.json
> +{
Det er en fordel om alle bruker yarn og ikkje npm for då unngår vi å ha både package-lock.json og yarn.lock.

2022-02-04 15:39 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-nb.ts
> +        letterFilter: 'Hvis innhald på (bokstaven) {{letter}}.',
```suggestion
        letterFilter: 'Vis innhald på (bokstaven) {{letter}}.',
```

2022-02-22 15:34 UTC, gunnarvelle commented on packages/ndla-notion/src/NotionHeader.tsx
> +      )}
Dette heng ikkje sammen med endringene her https://github.com/NDLANO/frontend-packages/pull/1026.

2022-02-24 11:06 UTC, gunnarvelle approved these changes
LGTM

2022-03-01 14:11 UTC, merged