Added new beta and outdated messages for messagebox
NDLANO/frontend-packages pull request #1082
Opened 2022-03-29 13:14 UTC by Jonas-C

Trengs for https://github.com/NDLANO/ndla-frontend/pull/952
Relatert til https://github.com/NDLANO/Issues/issues/3049

2022-03-29 14:15 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-nb.ts
> +    subjectBeta: 'Dette faget er i beta og vil være klart til skolestart.',
Burde det stå betaversjon også på bokmål?

2022-03-30 06:18 UTC, Jonas-C commented on packages/ndla-ui/src/locale/messages-nb.ts
> +    subjectBeta: 'Dette faget er i beta og vil være klart til skolestart.',
Disse er dratt rett ut fra språkdokumentet de linket til i Trello. Kan godt endre det til betaversjon hvis du vil!

2022-03-30 06:22 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-nb.ts
> +    subjectBeta: 'Dette faget er i beta og vil være klart til skolestart.',
Tenkte konsistens var viktig, men då må vi spørre på trello igjen.

2022-04-01 06:05 UTC, gunnarvelle requested changes

2022-04-01 06:05 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-nb.ts
> +    subjectBeta: 'Dette faget er i beta og vil være klart til skolestart.',
Sjekka dokumentet igjen og det står betaversjon der. Trur også at den korte varianten er best i tilfelle enkelte fag likevel ikkje er klare til skulestart.
```suggestion
    subjectBeta: 'Dette faget er i betaversjon.',
```

2022-04-01 06:05 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-en.ts
> +    subjectBeta: 'This course is in beta and will be complete by the beginning of the next school year.',
```suggestion
    subjectBeta: 'This course is in beta.',
```

2022-04-01 06:05 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-nn.ts
> +    subjectBeta: 'Dette faget er i betaversjon og vil vere klart til skulestart.',
```suggestion
    subjectBeta: 'Dette faget er i betaversjon.',
```

2022-04-01 06:09 UTC, gunnarvelle approved these changes

2022-04-01 06:13 UTC, merged