Min ndla   resources
NDLANO/frontend-packages pull request #1130
Opened 2022-05-23 08:30 UTC by peterrolfsen

2022-05-23 11:42 UTC, gunnarvelle commented on packages/ndla-icons/svg/contentType/horizontalMenu.svg
> +</svg>;
Semilkolon for masse.

2022-05-23 11:42 UTC, gunnarvelle commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +                {' '}
Tipper denne skal bort. Ser ut som formatering med whitespace.

2022-05-23 11:42 UTC, gunnarvelle commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +                    <span></span>
Denne skal gjerne ikkje være med?

2022-05-23 12:56 UTC, peterrolfsen commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +                    <span></span>
![image](https://user-images.githubusercontent.com/25527932/169824108-30866914-3b25-400c-af0a-ea4646c096d5.png)
Det er med i designet. Er det besluttet å ta bort?

2022-05-23 19:43 UTC, IvarBorthen requested changes

2022-05-23 19:43 UTC, IvarBorthen commented on packages/ndla-ui/src/MyNdla/ResourceDash/Folderelement.tsx
> +  &visited {
Skulle det vært &:visited? Eller skal den fjernes?

2022-05-23 19:43 UTC, IvarBorthen commented on packages/ndla-ui/src/MyNdla/ResourceDash/Folderelement.tsx
> +const MoreIcon = styled(HorizontalMenu)<{ layout: LayoutProps }>`
Bruke IconButton istedet?

2022-05-23 19:43 UTC, IvarBorthen commented on packages/ndla-ui/src/MyNdla/ResourceDash/Folderelement.tsx
> +        <MoreIcon layout={layout} aria-label={t('myNdla.more')} />
Denne må enten være en React component passed som props eller så må den ha ResourceElement ha en onClickMore event som sender med id'en i en callback

2022-05-23 19:43 UTC, IvarBorthen commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +      transition: all 0.2s ease-in-out;
bruke animations.durations her? + trenger ikke spesifisere alle prefixene til transition

2022-05-23 19:43 UTC, IvarBorthen commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +    <ResourceElementWrapper to={link} layout={layout}>
Jeg tror vi bør omstrukturere litt for å forbedre UU. Se gjerne på Læringsressurser komponenten. Hit area bør begrenses til kun tekst på ressurs / evt med bilde. Den bør trolig også ha en aria-label? Itillegg forenkler vi det med ... (more) lenken osv

2022-05-23 19:43 UTC, IvarBorthen commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +                  <>
Fjern empty fragment </> wrapper og legg til en key i map loopen

2022-05-24 05:16 UTC, gunnarvelle commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +                    <span></span>
Jepp. Såg berre en tom span.

2022-05-24 06:40 UTC, peterrolfsen commented on packages/ndla-ui/src/MyNdla/ResourceDash/Folderelement.tsx
> +  padding: 0.5rem;
Trenger denne spesifikt for å holde den grå bakgrunnen rundt.  spacing sine verdier gjør den oval. 
<img width="68" alt="image" src="https://user-images.githubusercontent.com/25527932/169965147-09c05096-4b89-4718-beda-b3d73a66a534.png">

2022-05-24 08:16 UTC, haattis reviewed
Mengden kode kan reduseres en del. Generelle tiltak:
- Sett padding/margin på container heller enn å sette margin på hvert enkelt element.
- Unngå bruk av fastsatt height og width (gjelder stort sett tilfellene med prosent).
- Funksjonaliteten i flex (og eventuelt grid) kan brukes til å løse punktene over

Annet:
- Bilder i listevisning er ikke nå tilpasset høye eller brede bilder. Spesielt høye bilder strekker seg ut av skjermen.

2022-05-24 08:54 UTC, peterrolfsen commented on packages/ndla-ui/src/MyNdla/ResourceDash/Folderelement.tsx
> +const FolderIconCircle = styled.div<{ layout: LayoutProps }>`
Dette er ikke en knapp. Det er bare et icon.

2022-05-24 11:23 UTC, haattis commented on packages/ndla-ui/src/MyNdla/ResourceDash/Folderelement.tsx
> +const FolderIconCircle = styled.div<{ layout: LayoutProps }>`
Godt poeng. Jeg gjenkjente bare den liknende stylingen 😅

2022-05-24 11:32 UTC, peterrolfsen commented on packages/ndla-ui/src/MyNdla/ResourceDash/Folderelement.tsx
> +  -webkit-line-clamp: 1; /* number of lines to show */
Akkurat på denne må jeg har webkit for at den skal fungere.

2022-05-24 11:42 UTC, IvarBorthen commented on packages/ndla-ui/src/MyNdla/ResourceDash/ResourceElement.tsx
> +    <ResourceElementWrapper to={link} layout={layout}>
Vi skipper dette, har gjort en avsjekk med Phillipa så skal være ok

2022-05-26 10:18 UTC, merged