added new codeblokk, removed old file
NDLANO/frontend-packages pull request #1597
Opened 2023-03-23 10:52 UTC by John-H-Christiansen

2023-03-23 11:47 UTC, gunnarvelle commented
Kjør `yarn format` og `yarn check-all` for å passe på at koden er i henhold til standardoppsettet vårt.

2023-03-23 14:00 UTC, gunnarvelle commented
Eg får fremdeles endringer lokalt når eg kjører `yarn format` på denne branchen.

2023-03-29 06:49 UTC, gunnarvelle commented on packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
> +import * as React from 'react';
Lisens

2023-04-14 06:39 UTC, gunnarvelle commented
Ping! Kan godt gjøre ferdig denne.

2023-05-26 07:22 UTC, gunnarvelle commented
Finner ikkje kodeblokk i storybook.

2023-05-31 09:27 UTC, gunnarvelle commented
ActionButton er for at du skal kunne sende inn et X-ikon i ed for å fjerne kodeblokken. Det gir meir meining om det styles med en IconButton i stedet for en Button.

2023-05-31 09:42 UTC, gunnarvelle commented on packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
Lisens

2023-05-31 09:42 UTC, gunnarvelle commented on packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
> +    actionButton: <ButtonV2>Button</ButtonV2>,
```suggestion
    actionButton: 
    <IconButtonV2 aria-label="Slett" variant="ghost" colorTheme="danger">
      <DeleteForever/>
    </IconButtonV2>,
```

2023-05-31 09:42 UTC, gunnarvelle commented on packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
> +  },
```suggestion
  },
    argTypes: {
    actionButton: {
      control: {
        type: null,
      },
    },
  },
```

2023-05-31 09:44 UTC, gunnarvelle commented
Samtidig kunne dokke sikkert endra typen på actionButton fra JSX.element til ReactNode.

2023-05-31 10:15 UTC, bouvetbrynjulfsen commented on packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
> +  },
Nais, skal fikse!

2023-05-31 10:49 UTC, bouvetbrynjulfsen commented
> Samtidig kunne dokke sikkert endra typen på actionButton fra JSX.element til ReactNode.

Vurderte også å endre `format` til en liste med godkjente strings, en for hvert av språkene som er tilgjengelig. Eller er det overkill? 

Type sånn: 
`format: "bash" | "c" | "csharp" | "css" | "diff" | "html" ...`

2023-05-31 10:59 UTC, bouvetbrynjulfsen commented
> Vi har jo en oversikt over språk i languageOptions, men er usikker på om det er uttømmende.

Ja, det er sant 🤔 Der finnes for eksempel ikke `html`, bare `markup`, så jeg klarer ikke helt å se hvordan den pakken fungerer. Jeg lar det ligge inntil videre i hvert fall

2023-05-31 12:02 UTC, gunnarvelle commented on packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
Mangler fremdeles lisens her.

2023-05-31 14:59 UTC, Jonas-C commented on packages/ndla-code/src/Codeblock/Codeblock.tsx
> +  actionButton?: ReactNode | null;
Trenger nok ikke `| null` her.

2023-06-01 07:51 UTC, bouvetbrynjulfsen commented on packages/ndla-code/src/Codeblock/Codeblock.tsx
> +  actionButton?: ReactNode | null;
Notert, jeg fikser 👍

2023-06-01 08:20 UTC, Jonas-C commented on stories/codeblock/CodeblockExample.jsx
Denne filen kan vel forsvinne nå? Såvidt jeg vet brukes den ikke noen andre steder enn i simple-components. Da må dere isåfall fjerne importen i simple-components.

2023-06-01 13:02 UTC, gunnarvelle requested changes
Legg til lisens i stories og fjern example-fila.

2023-06-02 13:40 UTC, bouvetbrynjulfsen commented on packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
Fikset 👍

2023-06-02 13:45 UTC, gunnarvelle approved these changes

2023-06-05 07:21 UTC, merged