script for å switche gjemt video
NDLANO/frontend-packages pull request #820
Opened 2021-06-08 10:12 UTC by OliverKnowit

2021-06-08 10:17 UTC, gunnarvelle commented on packages/ndla-ui/src/Figure/Figure.js
> +          </button>
Det er vel ikkje gitt at en video har en synstolka versjon. Så du må vel ha en prop som styrer det. I tillegg i18n.

2021-06-08 11:13 UTC, OliverKnowit commented on packages/ndla-ui/src/Figure/Figure.js
> +          </button>
true

2021-06-16 11:34 UTC, gunnarvelle commented on packages/ndla-ui/src/Figure/Figure.js
> +              <span>Bytt til synstolket</span>
i18n, pluss at knappen bør bytte tekst dersm det er synstolket du viser.

2021-06-16 11:35 UTC, gunnarvelle reviewed
Skriv også gjerne om til ts om det passer slik.

2021-06-16 11:35 UTC, gunnarvelle commented on packages/ndla-ui/src/Figure/Figure.js
> +  sysntolketVideo: PropTypes.bool,
typo.
```suggestion
  synstolketVideo: PropTypes.bool,
```

2021-06-21 08:26 UTC, gunnarvelle requested changes
Mangler fremdeles i18n for tekst på knapp.

2021-06-21 08:31 UTC, OliverKnowit commented
> Mangler fremdeles i18n for tekst på knapp.

Ja, jeg prøver å finne ut av hvordan jeg skal endre teksten basert på hva som vises. Lurer på om jeg må gjøre det i scriptet også

2021-06-22 13:01 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-nb.ts
> +  },
Ta med disse i messages-nn og messages-en også.

2021-06-23 09:48 UTC, gunnarvelle commented on packages/ndla-ui/src/Figure/Figure.js
> +    synstolketVideo,
Eg er sikkert firkanta, men synes det ser litt rart ut med en norsk prop sammen med alle dei andre engelske.

2021-06-23 09:48 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-en.ts
> +      synstolket: 'Switch to visually interpretted video',
```suggestion
      synstolket: 'Switch to visually interpreted video',
```

2021-06-23 09:48 UTC, gunnarvelle commented on packages/ndla-ui/src/locale/messages-nn.ts
> +      synstolket: 'Bytt til synstolket',
```suggestion
      synstolket: 'Bytt til synstolka',
```

2021-06-23 09:52 UTC, OliverKnowit commented on packages/ndla-ui/src/Figure/Figure.js
> +    synstolketVideo,
Jeg bare kom ikke på noe bra navn. "Interpret" var det nermeste, men det er ikke like beskrivende

2021-06-24 08:29 UTC, gunnarvelle commented on packages/ndla-ui/src/Figure/Figure.js
> +    synstolketVideo,
Kanskje showAlternativeVideo og toggleAlternativeVideo kunne brukes?

2021-06-28 12:04 UTC, gunnarvelle approved these changes

2021-06-28 12:07 UTC, merged