React swipeable update
NDLANO/frontend-packages pull request #918
Opened 2021-11-19 20:59 UTC by rfohlin

2021-11-23 12:28 UTC, beery approved these changes

2021-11-24 08:44 UTC, gunnarvelle reviewed
Litt småplukk.

2021-11-24 08:44 UTC, gunnarvelle commented on packages/carousel/types/react-swipeable.d.ts
> +/* declare module 'react-swipeable' {
Trengs denne fila om innholdet er kommentert ut?

2021-11-24 08:44 UTC, gunnarvelle commented on packages/carousel/src/Carousel.tsx
> +}) => {
Synes denne notasjonen er ryddigere:
```suggestion
export const Carousel = ({
  items = [],
  columnWidth,
  columnsPrSlide,
  slideBackwardsLabel,
  slideForwardsLabel,
  disableScroll,
  arrowOffset = 0,
  distanceBetweenItems = 0,
  margin = 0,
  buttonClass = '',
  wrapperClass = '',
}: Props) => {
```

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/FilmSlideshow.tsx
> +const FilmSlideshow: React.FC<Props> = ({ autoSlide = false, slideshow = [], slideInterval = 5000 }) => {
Samme som forrige.
```suggestion
const FilmSlideshow = ({ autoSlide = false, slideshow = [], slideInterval = 5000 }: Props) => {
```

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/NavigationArrow.tsx
> +const NavigationArrow: React.FC<Props> = ({ slideIndexTarget, gotoSlide, rightArrow }) => {
Og her.
```suggestion
const NavigationArrow = ({ slideIndexTarget, gotoSlide, rightArrow }: Props) => {
```

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/SlideshowIndicator.tsx
> +const SlideshowIndicator: React.FC<Props> = ({ slideshow, activeSlide, gotoSlide }) => {
Og her.
```suggestion
const SlideshowIndicator = ({ slideshow, activeSlide, gotoSlide }: Props) => {
```

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/shapes.ts
> +export interface IMovie {
Denne fila er en blanding av et typescript interface og en PropTypes shape. Hadde det ikkje vore bedre å legge til en interfaces.ts og legge interfacet der. Og når FilmMovieSearch gjøres om til TS så kan topicShape skrives om til interface, og denne fila slettes.

Er heller ikkje veldig glad i I som prefix på egne typer, men er ikkje farlig.

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/Spinner/Spinner.tsx
> +const Spinner: React.FC<Props> = ({ size = 'large', margin = `${spacing.normal} auto`, inverted = false }) => (
Samme.
```suggestion
const Spinner = ({ size = 'large', margin = `${spacing.normal} auto`, inverted = false }: Props) => (
```

I tillegg, dersom Spinner er gjort om fra js til ts så må eksporten flyttes fra index-javascript.js til index.ts.

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/SlideshowIndicator.tsx
> +          key={`indicator_${index}`} // eslint-disable-line react/no-array-index-key
Eslint-kommentaren trengs ikkje lenger.
```suggestion
          key={`indicator_${index}`}
```

2021-11-24 08:44 UTC, gunnarvelle commented on packages/carousel/src/CarouselAutosize.tsx
> +}) => {
Samme.
```suggestion
export const CarouselAutosize = ({
  breakpoints: propsBreakpoints,
  children,
  centered,
  itemsLength,
}: Props) => {
```

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/Subject/SubjectCarousel.tsx
> +            distanceBetweenItems={0}
Denne defaulter allerede til 0 i Carousel og er optional.

2021-11-24 08:44 UTC, gunnarvelle commented on packages/carousel/src/CarouselAutosize.tsx
> +  // Hooks
Unødvendig kommentar.

2021-11-24 08:44 UTC, gunnarvelle commented on packages/carousel/src/CarouselAutosize.tsx
> +      // @ts-ignore
ts-ignore inni en rein ts-komponent virker som en måte å unngå linting. Her bør du heller fikse koden.

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/FilmSlideshow.tsx
> +  // Hooks
Unødvendig kommentar.

2021-11-24 08:44 UTC, gunnarvelle commented on packages/ndla-ui/src/Spinner/Spinner.tsx
> +}
Trengs det meir enn ett interface her?

2021-12-14 10:54 UTC, gunnarvelle requested changes
Ser ikkje at det har skjedd noko her siden min review.

2022-01-05 13:28 UTC, gunnarvelle commented
Ping @rfohlin

2022-01-27 14:08 UTC, rfohlin commented on packages/carousel/types/react-swipeable.d.ts
> +/* declare module 'react-swipeable' {
Nej det har du rätt i, jag tar bort den.

2022-01-27 14:10 UTC, rfohlin commented on packages/carousel/src/Carousel.tsx
> +}) => {
Enig.

2022-01-28 07:40 UTC, gunnarvelle commented on packages/carousel/src/CarouselAutosize.tsx
> +      distanceBetweenItems: distanceBetweenItems,
Er ikkje dette en overflødig syntaks? Samme med margin rett under.

2022-01-28 07:40 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/SlideshowIndicator.tsx
> +  gotoSlide: Function;
Prøv å unngå Function, men heller definer signaturen
```suggestion
  gotoSlide: (indexTarget: number, useAnimation: boolean) => void;
```

2022-01-28 07:40 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/NavigationArrow.tsx
> +  gotoSlide: Function;
Unngå Function.
```suggestion
  gotoSlide: (indexTarget: number, useAnimation: boolean) => void;
```

2022-01-28 07:40 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/FilmSlideshow.tsx
> +  slideshow: Array<NDLAMovie>;
Alternativ definisjon
```suggestion
  slideshow: NDLAMovie[];
```

2022-01-28 07:40 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/FilmSlideshow.tsx
> +const renderSlideItem = (slide: any) => (
Her veit vi jo kva type dette er så det er bedre å være eksplisitt.
```suggestion
const renderSlideItem = (slide: NDLAMovie) => (
```

2022-01-28 07:40 UTC, gunnarvelle commented on packages/ndla-ui/src/NDLAFilm/SlideshowIndicator.tsx
> +  slideshow: Array<NDLAMovie>;
Forslag
```suggestion
  slideshow: NDLAMovie[];
```

2022-01-28 07:52 UTC, gunnarvelle commented
Fikk forresten en endring i yarn.lock då eg kjørte yarn lokalt.

2022-02-02 11:58 UTC, gunnarvelle commented
En konflikt i package-json. Fint om du fikser slik at vi kan teste pr-installasjon.

2022-02-02 13:36 UTC, gunnarvelle approved these changes
LGTM

2022-02-03 09:03 UTC, merged